pipeline {
    agent { label "Jenkins-Agent" }
    environment {
              APP_NAME = "register-app-pipeline"
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
               steps {
                   git branch: 'main', credentialsId: 'github', url: 'https://github.com/adkrbuss-ops/Devops-MavenRegister-app.git'
               }
        }

        stage("Update the Deployment Tags") {
               steps {
                   sh """
                      sed -i '/image:/s|${APP_NAME}:.*|${APP_NAME}:${IMAGE_TAG}|' K8s-manifestFile/deployment.yaml

                      grep image K8s-manifestFile/deployment.yaml
                      """
                }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                sh """
                   git config --global user.name "adkrbuss-ops"
                   git config --global user.email "adkrbuss@gmail.com"
                   git add deployment.yaml
                   git commit -m "Updated Deployment Manifest"
                """
                withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                  sh "git push https://github.com/adkrbuss-ops/Devops-MavenRegister-app.git main"
                }
            }
        }
      
    }
}
